### ISSUE TITLE
PATH issue

### ISSUE THREAD

**Issue by grahampugh** [gkluoe/git2jss#19]
Hi, probably not an important one, but I recently screwed up my path experimenting with a Homebrew installation method, and afterwards `git2jss` failed with `OSError: [Errno 2] No such file or directory`. It came down to needing `/sbin` in my `$PATH`. I lazily have not gone through the code to determine which command is being run that doesn't specify the path, but it's somewhere :)

**Comment by geoffklee** [comment]
I'm stumped by this one. The only external things we call are `git` and `plutil` - `git` is deliberately called as just `git`, so that it uses whatever's in your path. `plutil` also shouldn't be in `/sbin`, in fact there's very little in `/sbin`. I'm not calling `ping`... 

Hmm. If you can reproduce I'm happy to investigate though :-)
